#!/usr/bin/env bash
set -euo pipefail

# As of 0.13, xmonad --recompile will look for a custom build script.

stack build :my-xmonad --verbosity error
stack install :my-xmonad --local-bin-path bin/ --verbosity error
mv bin/my-xmonad "$1"
