name: Build
on:
  # Needs to be triggered manually
  workflow_dispatch:
    inputs:
      pkgs:
        description: "Nixpkgs to build with"
        required: false
        default: "channel:nixos-unstable"

jobs:
  build_and_cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4

      - uses: cachix/install-nix-action@v12
        with:
          nix_path: "nixos=${{ github.event.inputs.name }}"

      - name: Build
        run: nix-build -o result

      - name: Sign
        run: |
          echo ${{ secrets.CACHIX_SIGNING_KEY }} > secret.key
          nix sign-paths --key-file secret.key --recursive $(readlink result)

      - name: Push
        run: nix copy --to s3://jmackie-nixos-cache?region=eu-west-1 $(readlink result)
